name: Remote Backup
version: "2022.7.2"
slug: remote_backup
description: Automatically create and backup HA backups using SCP
image: ikifar/remote-backup-{arch}
url: https://addons.mathesonsteplock.ca/docs/addons/remote-backup/basic-config
codenotary: cas@mathesonsteplock.ca
startup: once
boot: manual
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant: "2021.9.0"
hassio_api: true
hassio_role: manager
map:
  - config
  - addons
  - share
  - ssl
  - backup:rw
  
options:
  debug: false
  remote_host: ""
  remote_port: 22
  remote_user: ""
  remote_password: ""
  remote_key: ""
  remote_host_key_algorithms: ""
  backup_friendly_name: true
  backup_custom_prefix: Automated backup
  backup_exclude_folders: []
  backup_exclude_addons: []
  backup_keep_local: "all"
  backup_password: ""
  ssh_enabled: true
  ssh_remote_directory: ""
  rsync_enabled: false
  rsync_rootfolder: hassio-sync
  rsync_exclude:
    - "/config/*.db-shm"
    - "/config/*.db-wal"
    - "/config/*.db"
  rclone_enabled: false
  rclone_remote_directory: ""
  rclone_copy: false
  rclone_sync: false
  rclone_restore: false

schema:
  debug: bool?
  remote_host: str
  remote_port: port
  remote_user: str
  remote_password: str?
  remote_key: str?  
  remote_host_key_algorithms: str?
  backup_friendly_name: bool?
  backup_custom_prefix: str?
  backup_exclude_folders:
    - match(^[A-Za-z0-9_\-\.\*\/\?\+\\]*$)?
  backup_exclude_addons:
    - str?
  backup_keep_local: match(^(all|[+]?\d*)$)
  backup_password: str?
  ssh_enabled: bool
  ssh_remote_directory: str?
  rsync_enabled: bool
  rsync_rootfolder: str?
  rsync_exclude:
    - match(^[A-Za-z0-9_\-\.\*\/\?\+\\]+$)
  rclone_enabled: bool
  rclone_remote_directory: str?
  rclone_copy: bool?
  rclone_sync: bool?
  rclone_restore: bool?
