# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master
pr:
  branches:
    include:
    - '*' 
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    ls -al
    docker run --rm --privileged -v ~/.docker:/root/.docker -v /var/run/docker.sock:/var/run/docker.sock:ro -v /remote-backup:/data homeassistant/amd64-builder --all --test -t /data
  displayName: 'Run a multi-line script'
