# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Default'
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo hi
    docker run --rm --privileged -v ~/.docker:/root/.docker -v /var/run/docker.sock:/var/run/docker.sock:ro homeassistant/amd64-builder --all -t remote-backup -r https://github.com/ikifar2012/remote-backup-addon -b master --docker-user $DOCKERUSER --docker-password $DOCKERPASS
  displayName: 'Run a multi-line script'
  env:
    DOCKERUSER: $(dockeruser)
    DOCKERPASS: $(dockerpass)