# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  dockeruser: $(dockeruser)
  dockerpass: $(dockerpass)
trigger:
- master

pool:
  name: 'Default'
  vmImage: 'ubuntu-latest'

steps:
- script: |
    docker run --rm --privileged -v ~/.docker:/root/.docker -v /var/run/docker.sock:/var/run/docker.sock:ro homeassistant/amd64-builder --all -t remote-backup -r https://github.com/ikifar2012/remote-backup-addon -b master --docker-user $(dockeruser) --docker-password $(dockerpass)
  displayName: 'Run a multi-line script'
env:
  dockeruser: $(dockeruser)
  dockerpass: $(dockerpass)